
package pt.gesmarapp.model;

public class Morada {
     
String rua;            //Exemplo: Rua Francisco George,.....
String NPorta;         //Exemplo: Número da porta
String piso;           //Exemplo: andar caso exista.....
String codigoPostal;   //Exemplo: 001:Tétano.....
String freguesia;      //Exemplo: Olivais: 
String concelho;       //Exemplo: Loures,Odivelas.....
String distrito;       //Exemplo: Lisboa,Porto....   
}
